name: Build Public XML

on:
  push:
    branches: [ main, ci-build ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Run public-xml-build script
      run: .\site-build.ps1
      shell: powershell
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: tipitaka-site-build
        path: tipitaka-site-build.zip
        retention-days: 15  # Keep only for 15 days (or adjust as needed)
        compression-level: 0  # Skip compression since it's already a .zip